### ISSUE TITLE
COG unable to detect Deep Dark

### ISSUE THREAD

**Issue by reteo** [lawremi/CustomOreGen#144]
World: Deep Dark (Underdark)
dimension.generator.class = "ChunkProviderUnderdark"

While attempting to make a configuration for the Deep Dark, I discovered that COG is not generating any distributions in the world.  ChunkProviderUnderdark is the world generator class, but for whatever reason, COG doesn't behave as if it detected this; in the Deep Dark, even the debugging wireframes are not showing up.

I honestly don't know if this is a problem with COG, or something on ExU's side blocking detection of the class, but I thought I should report this.

**Comment by lawremi** [comment]
Is COG active? Does /cogInfo work? My guess is that deep dark does not call standard forge hooks.

**Comment by reteo** [comment]
It is active, and /coginfo does seem to work.  In addition, the wireframe mode does show the world floor (the green squares) just fine, but it does not show any other wireframes, meaning that, for whatever reason, the mod is working, but not generating (or substituting) anything.

**Comment by lawremi** [comment]
I'm pretty sure that Extra Utilities is just not allowing for standard ore generation in that dimension. See https://github.com/rwtema/extrautilities/issues/680. The Deep Dark is supposed to double ore generation. I'm guessing that applies only to vanilla ores, where the frequencies are doubled, instead of running the generators twice. It's a closed source mod, so it's only a guess. Not much I can do.
