### ISSUE TITLE
Ores are removed from Recurrent Complex structures.

### ISSUE THREAD

**Issue by nmarshall23** [lawremi/CustomOreGen#149]
I'm using the Recurrent Complex Mod to create structures, some of those are buildings with Ore blocks inside them. However CustomOreGen replaces those Ores with just Stone.

**Comment by reteo** [comment]
Unfortunately, that's the default behavior of Custom Ore Generation; this allows it to counter those mods that refuse to include the option to switch off their oregen in the configuration.

In order to disable that feature, you need to edit the XML files (moving them into the custom folder and disabling them in the main `CustomOreGen_Config.xml` file) to remove the substitution step at the beginning of the dimension's configuration.  However, if you do that, you'll need to make sure all your mods with oregen have their generation disabled, or COG will be mixed with the default sprinkle.

**Comment by lawremi** [comment]
Assuming that Recurrent Complex only places vanilla ores, one solution would be to enable debug options and turn off "Vanilla Ore Gen". That intercepts vanilla ore generation prior to the blocks even being placed. It used to be that the vanilla configuration would disable its substitute distributions when vanilla ore gen was intercepted in that way. Unfortunately, the new auto-generated config does not have the condition. It looked like this:

```
<IfCondition condition=':= vanillaOreGen'>
        <Substitute name='StandardOreSubstitute' block='minecraft:stone'>
```

@reteo is there any way that your sprocket tool could handle that special case?

**Comment by reteo** [comment]
Done.
