### ISSUE TITLE
COG Packet Crash

### ISSUE THREAD

**Issue by Draco18s** [lawremi/CustomOreGen#171]
These occurred at different times, but they all appeared to be related to COG's networking handler.  Only occurs with wireframes turned on.  One client side and two server side.

http://pastebin.com/zsf3uzmX (ArrayIndexOutOfBoundsException: -1)
http://pastebin.com/Ws0KVhPr (ArrayIndexOutOfBoundsException: 1536)
http://pastebin.com/arSEg8U3 (Invalid or corrupt compressed vector (196650))

**Comment by lawremi** [comment]
The first one is pretty revealing, in that COG is attempting to generate upon receiving a geometry data request. Since generation is happening concurrently, things will fail. It seems sensible to not force any generation in the networking handlers. The latter two crashes were already mentioned in #164.

**Comment by Draco18s** [comment]
Yeah, saw 164 after I posted.
