### ISSUE TITLE
Compatibility with BiomesOPlenty 1.10.2.5

### ISSUE THREAD

**Issue by BenjKl** [lawremi/CustomOreGen#177]
No Ores are generated by CustomOreGen   (Vanilla and Mods) when world type is BiomesOPlenty. Neither in new nor in vanilla biomes.

**Comment by lawremi** [comment]
@reteo I think we should use the `dimension` property to decide on the dimension type. In 1.10, there is a formal notion of dimension type (Overworld, Nether, End by default) and that is now mapped to `dimension` since dimension-specific names have apparently gone away. In other words, use `dimension="Nether"` instead of `dimension.generator.class="ChunkProviderHell"`.

**Comment by BenjKl** [comment]
Thank you. That helped!

**Comment by reteo** [comment]
At this point, I'm going to have to drop the configuration work.  I'm making configurations for a version of Minecraft that I don't play (not that I'm even playing Minecraft much anymore), which makes the whole project feel like an unpaid job, and I'm getting burned out.  Feel free to fork (or remake) the Sprocket toolkit for your own use if it helps; it's open to everyone's use and modification (GPL License).

**Comment by lawremi** [comment]
Ok, thanks all of your contributions. I don't play Minecraft anymore either, so I understand your perspective.
