### ISSUE TITLE
Defaults By Ore Type

### ISSUE THREAD

**Issue by IMarvinTPA** [lawremi/CustomOreGen#57]
It would be handy to minimize the number or Copper Ores generated if there were ore-type specific default config files that list all of the known sources of Copper and tweak that.  Ideally, it just asks how much copper you want and with creative use of ifChoice it only generate one mod's Copper and none of the others.

A separate file per material would be handy.  I may try to do this myself just to help understand what's going on.

**Comment by Taschenmogul** [comment]
I like the idea though I want to comment that it should give a little more performance if you disable the generation of a mods ore directly in its config file so that it is not generated in the first place.
Because if it is not generated at all you can also deactivate the substitution distributions that replace the originally generated ores with stone which in turn should give you slightly better worldgen performance.

**Comment by IMarvinTPA** [comment]
I have a script filling in a template with data I've put together in a database.
the top of each file starts off with something like this:
<IfCondition condition=":=isModInstalled('BiomesOPlenty') | isModInstalled('Thaumcraft')">
then in the ore gen areas I have
<OreBlock weight='1'>
			<IfModInstalled name='BiomesOPlenty'><block>BiomesOPlenty:gemOre:14</block></IfModInstalled>
            <IfModInstalled name='Thaumcraft'><block>Thaumcraft:blockCustomOre:7</block></IfModInstalled> 
		</OreBlock>

In the substitution areas, I generally use ore dictionary names since that's how I found the ores in the first place.  Such as:
<ReplacesOre block='oreAmber' />

Which is doubly handy since it will replace any unexpected mods that use that ore dictionary name but still replace it with what we know to use.

Thanks,
IMarv

**Comment by IMarvinTPA** [comment]
I have made some files that I think are good enough.  I did not base them too closely on the generations that are in the old defaults, so feel free to tweak these more.  My files are at http://www.imarvintpa.com/CustomOres/CustomOreGen.zip
Thanks,
IMarv

**Comment by lawremi** [comment]
Ok, thanks. What if COG just gained a `OreName` element, or something, as an alternative to `OreBlock`. It would just take the first block registered under that name in the ore dictionary. Not sure how predictable it would be (depends on the mod load order), but at least it would be totally mod independent. If I added that, would you update these configs? 

Btw, I'm not so sure replacing limestone, marble, etc, is the right thing, because most ores will look out of place embedded within a different stone type, and really, the limestone deposit represents a discontinuity, so the vein should be broken.

**Comment by IMarvinTPA** [comment]
Most of the files were totally database-script generated, so updating to use an OreName element would be pretty easy.  The NetherOres are each modified simply (to detect if both any mod using the Ore and Nether Ores is installed.)  So if you add OreName, also add a way to detect if a dictionary name exists would by handy, then I can just use that to enable a file.  The Uranium one is the most unique in that it uses 6 different OreBlocks to generate 1/3, 1/2, or all of one based upon if Yellorium, Uranium, and Pitchblende are installed or not.  I've been contemplating if I should somehow add some Poor Ores to the normal ones.

Is there a hard limit of 255 distributions somewhere?  Early on, I had more and thought it was odd that it stopped there.  (I culled it by moving all substitutions into one file, which I think helps performance anyway.)
IMarv

**Comment by lawremi** [comment]
Next release will support `<FirstOreDictBlock block='oreCoal'/>`, and `<IfOreExists name="oreCoal"/>`. We might need an easier way to handle the case when an ore does not exist. Like a fallback to some specified block, like stone. Also, I've managed to get this to work with Gregtech, without any need for the user to mess with NBT.

**Comment by IMarvinTPA** [comment]
The files currently start with <IfCondition condition=":=isModInstalled('GalacticraftCore') | isModInstalled('Steamcraft') | isModInstalled('ElectriCraft') | isModInstalled('emashercore') | isModInstalled('Forestry') | isModInstalled('Mekanism') | isModInstalled('TConstruct') | isModInstalled('Metallurgy') | isModInstalled('IC2') | isModInstalled('ThermalFoundation')">
They will instead start with <IfOreExists name="oreCopper"/>.

In the case of using a FirstOreDictBlock when the ore doesn't exist, it should throw an error screen error to help you debug it.  Pam's salt ore isn't in the dictionary as oreSalt.  (I don't think it is in the dictionary at all.)

IMarv

**Comment by lawremi** [comment]
Yea, she had it registered as `oreSalt` but then dropped it, according to this: http://minecraft.curseforge.com/mc-mods/221857-pams-harvestcraft/files/2223550. So we might need to handle salt manually with `blockExists()`.

**Comment by lawremi** [comment]
Here are some thoughts for how to move forward. Let's create a config that has a "Universal mode" option, with choices for "Realistic", "Original COG" and "Disabled". The "Realistic" config would obviously use more realistic patterns, with less user control. It would also try to use more technical ores like "magnetite" and "hematite" specifically, instead of just "iron", as long as they exist. The "Original COG" option would be like the current config, but mod agnostic. We will also disable all mod-specific generation of ores that are included in the universal config. The user can re-enable if desired.

**Comment by IMarvinTPA** [comment]
Is there an expression like "oreExists" similar to "blockExists" or must it be a node?

In my version of the oregen config, I moved oreDist to the top level so I could change all of them at once.  My configs do not duplicate the original COGs very closely at all, more like multiply off of factors of generic generation values and adjust the iron distributions.  Anyway, oreDist has vanillaStdGen which kinda maps to vanilla, layeredVeins is the default for COG, and strategicClouds is the weird one.  Anyway, that would be a good place to start to adjust the behaviors.

IMarv

**Comment by lawremi** [comment]
Refactoring the options makes sense. I was just talking about the shape/size/frequency of the distributions. We can change things, but we should be careful, I guess.

**Comment by IMarvinTPA** [comment]
I just mean that I kinda already have global differences built into my templates.  Just let me know if there should be more.  A sample is like such:
IfCondition condition=':= if(age, age.$OreDictName$Veins > 0 | 
					(age.$OreDictName$Clusters = 0 &amp; age.$OreDictName$Clouds = 0 &amp; 
					( ($OreDictName$Dist = "default" &amp; oreDist = "layeredVeins") | $OreDictName$Dist = "layeredVeins"))
					, ( ($OreDictName$Dist = "default" &amp; oreDist = "layeredVeins") | $OreDictName$Dist = "layeredVeins"))'

I got too worn out trying to extract the numbers that make the different types from the mod-based config files, if we want those back, somebody else will need to update the files I provide next.  I just want to test them before I turn them in, unless you need them to test with first.

Thanks,
IMarv

**Comment by lawremi** [comment]
No reason to do anything with `age`. The Mystcraft support has not worked since MC 1.4.2. That should simplify your conditions considerably.

**Comment by lawremi** [comment]
I think with `FirstOreBlock` and `IfOreExists`, it should be easy to implement a config like this. Not sure it's of general interest though since the generated block is arbitrary. Closing.

**Comment by reteo** [comment]
Actually, if it helps, I keep notes about all the ores I've generated over the course of my work.  You can find details, including calculations, and original vanilla values [here](https://github.com/reteo/Sprocket/blob/master/COG%20Ore%20Settings%20Chart.ods).
